# Generated by Django 4.2.7 on 2025-07-25 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template_editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('html_content', models.TextField(help_text='Complete HTML template with embedded CSS and JavaScript')),
                ('preview_image', models.ImageField(blank=True, upload_to='template_previews/')),
                ('music_url', models.URLField(blank=True, help_text='URL to background music')),
                ('music_file', models.FileField(blank=True, upload_to='template_music/')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='template_editor.templatecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='template',
            name='music_file',
            field=models.FileField(blank=True, help_text='Background music file', upload_to='template_music/'),
        ),
        migrations.AddField(
            model_name='template',
            name='music_url',
            field=models.URLField(blank=True, help_text='Background music URL'),
        ),
        migrations.CreateModel(
            name='Undangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('nama_panggilan_pria', models.CharField(max_length=100)),
                ('nama_panggilan_wanita', models.CharField(max_length=100)),
                ('nama_lengkap_pria', models.CharField(max_length=255)),
                ('nama_lengkap_wanita', models.CharField(max_length=255)),
                ('info_orang_tua_pria', models.CharField(blank=True, max_length=255)),
                ('info_orang_tua_wanita', models.CharField(blank=True, max_length=255)),
                ('foto_pria', models.ImageField(blank=True, upload_to='couple_photos/')),
                ('foto_wanita', models.ImageField(blank=True, upload_to='couple_photos/')),
                ('foto_cover', models.ImageField(blank=True, upload_to='cover_photos/')),
                ('file_musik', models.FileField(blank=True, upload_to='wedding_music/')),
                ('kutipan_pembuka', models.TextField(blank=True)),
                ('sumber_kutipan', models.CharField(blank=True, max_length=255)),
                ('teks_pengantar_cerita', models.TextField(blank=True)),
                ('teks_pengantar_acara', models.TextField(blank=True)),
                ('teks_pengantar_galeri', models.TextField(blank=True)),
                ('teks_pengantar_hadiah', models.TextField(blank=True)),
                ('teks_pengantar_rsvp', models.TextField(blank=True)),
                ('teks_penutup', models.TextField(blank=True)),
                ('judul_acara_1', models.CharField(blank=True, max_length=100)),
                ('tanggal_waktu_acara_1', models.DateTimeField(blank=True, null=True)),
                ('waktu_selesai_acara_1', models.TimeField(blank=True, null=True)),
                ('nama_lokasi_acara_1', models.CharField(blank=True, max_length=255)),
                ('alamat_lokasi_acara_1', models.TextField(blank=True)),
                ('link_gmaps_acara_1', models.URLField(blank=True)),
                ('judul_acara_2', models.CharField(blank=True, max_length=100)),
                ('tanggal_waktu_acara_2', models.DateTimeField(blank=True, null=True)),
                ('waktu_selesai_acara_2', models.TimeField(blank=True, null=True)),
                ('nama_lokasi_acara_2', models.CharField(blank=True, max_length=255)),
                ('alamat_lokasi_acara_2', models.TextField(blank=True)),
                ('link_gmaps_acara_2', models.URLField(blank=True)),
                ('custom_html_content', models.TextField(blank=True, help_text='Customized HTML content based on template and user data')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='template_editor.invitationtemplate')),
            ],
            options={
                'verbose_name': 'Undangan',
                'verbose_name_plural': 'Undangan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kejadian', models.DateField()),
                ('judul_kejadian', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
                ('kelas_ikon', models.CharField(blank=True, help_text="CSS class for icon (e.g., 'fa-heart')", max_length=50)),
                ('undangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_items', to='template_editor.undangan')),
            ],
            options={
                'ordering': ['tanggal_kejadian'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemilik', models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], max_length=10)),
                ('url_profil', models.URLField()),
                ('kelas_ikon', models.CharField(help_text="CSS class for social media icon (e.g., 'fab fa-instagram')", max_length=50)),
                ('undangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='template_editor.undangan')),
            ],
        ),
        migrations.CreateModel(
            name='GuestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tamu', models.CharField(max_length=255)),
                ('ucapan', models.TextField()),
                ('kehadiran', models.CharField(choices=[('Hadir', 'Hadir'), ('Tidak Hadir', 'Tidak Hadir'), ('Belum Pasti', 'Belum Pasti')], max_length=20)),
                ('waktu_kirim', models.DateTimeField(auto_now_add=True)),
                ('undangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_comments', to='template_editor.undangan')),
            ],
            options={
                'ordering': ['-waktu_kirim'],
            },
        ),
        migrations.CreateModel(
            name='GiftAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bank', models.CharField(max_length=100)),
                ('logo_bank', models.ImageField(blank=True, upload_to='bank_logos/')),
                ('nomor_rekening', models.CharField(max_length=50)),
                ('nama_pemilik', models.CharField(max_length=255)),
                ('undangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_accounts', to='template_editor.undangan')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='gallery_photos/')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('undangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='template_editor.undangan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
